/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.leave_management_v2.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.leave_management_v2.hrdb.models.query.AddLeaveBalRequest;
import com.leave_management_v2.hrdb.models.query.ApplyLeaveRequest;
import com.leave_management_v2.hrdb.models.query.ApproveRejectQueryRequest;

public interface HrdbQueryExecutorService {

    Integer executeAddLeaveBal(AddLeaveBalRequest addLeaveBalRequest);

    Integer executeApplyLeave(ApplyLeaveRequest applyLeaveRequest);

    Integer executeApproveRejectQuery(ApproveRejectQueryRequest approveRejectQueryRequest);

}