/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.leave_management_v2.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AddLeaveBalRequest implements Serializable {


    @JsonProperty("bal")
    @NotNull
    private Integer bal;

    @JsonProperty("id")
    @NotNull
    private Integer id;

    public Integer getBal() {
        return this.bal;
    }

    public void setBal(Integer bal) {
        this.bal = bal;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AddLeaveBalRequest)) return false;
        final AddLeaveBalRequest addLeaveBalRequest = (AddLeaveBalRequest) o;
        return Objects.equals(getBal(), addLeaveBalRequest.getBal()) &&
                Objects.equals(getId(), addLeaveBalRequest.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getBal(),
                getId());
    }
}