/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.leave_management_v2.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ApplyLeaveRequest implements Serializable {


    @JsonProperty("srt")
    @NotNull
    private Date srt;

    @JsonProperty("end")
    @NotNull
    private Date end;

    @JsonProperty("emp_id")
    @NotNull
    private Integer empId;

    @JsonProperty("status")
    @NotNull
    private String status;

    @JsonProperty("type")
    @NotNull
    private String type;

    public Date getSrt() {
        return this.srt;
    }

    public void setSrt(Date srt) {
        this.srt = srt;
    }

    public Date getEnd() {
        return this.end;
    }

    public void setEnd(Date end) {
        this.end = end;
    }

    public Integer getEmpId() {
        return this.empId;
    }

    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ApplyLeaveRequest)) return false;
        final ApplyLeaveRequest applyLeaveRequest = (ApplyLeaveRequest) o;
        return Objects.equals(getSrt(), applyLeaveRequest.getSrt()) &&
                Objects.equals(getEnd(), applyLeaveRequest.getEnd()) &&
                Objects.equals(getEmpId(), applyLeaveRequest.getEmpId()) &&
                Objects.equals(getStatus(), applyLeaveRequest.getStatus()) &&
                Objects.equals(getType(), applyLeaveRequest.getType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSrt(),
                getEnd(),
                getEmpId(),
                getStatus(),
                getType());
    }
}